### ISSUE TITLE
The code does no longer work with the current version of hyper

### ISSUE THREAD

**Issue by PetaSoft** [miquels/hyper-tls-hack#1]
Your implementation of hyper's AddrIncoming that generates TlsStreams does no longer work with the current version of hyper (0.14.8). I tried Your [example code in the documentation](https://miquels.github.io/hyper-tls-hack/hyper_tls_hack/) but it seems that `hyper::rt::Future` and `hyper::service::service_fn_ok` do not longer exist. I tried the following:
```rust
let addr = "127.0.0.1:8080".parse().unwrap();

let new_svc = make_service_fn(|_| async { Ok::<_, hyper::Error>(service_fn(handler)) });

let acceptor = Arc::new(acceptor_from_p12_file("cert.p12", "").unwrap());
let mut ai = AddrIncoming::new(&addr, acceptor, None).expect("addrincoming error");
ai.set_nodelay(true);
let server = Server::builder(ai).serve(new_svc);

println!("Listening on http://{}", addr);

if let Err(e) = server.await {
    eprintln!("server error: {}", e);
}
```
Unfortunately, I get the error messages: "the trait bound `hyper_tls_hack::AddrIncoming: Accept` is not satisfied - the trait `Accept` is not implemented for `hyper_tls_hack::AddrIncoming`. The error occurs at `serve(new_svc)` and `server.await`.
I tried to solve the problem by implementing `Accept` for `AddrIncoming` using the following code:
```rust
use hyper::server::accept::Accept;
use hyper::server::conn::AddrStream;
use core::pin::Pin;
use std::task;

macro_rules! ready {
  ($e:expr) => {
      match $e {
          std::task::Poll::Ready(v) => v,
          std::task::Poll::Pending => return std::task::Poll::Pending,
      }
  };
}

impl Accept for AddrIncoming {
  type Conn = AddrStream;
  type Error = io::Error;

  fn poll_accept(
      mut self: Pin<&mut Self>,
      cx: &mut task::Context<'_>,
  ) -> std::task::Poll<Option<Result<Self::Conn, Self::Error>>> {
      let result = ready!(self.poll_next_(cx));
      std::task::Poll::Ready(Some(result))
  }
}
```
I found the implementation in the source code of hyper 0.14.8 in the file `hyper-0.14.8/src/server/tcp.rs`.  There also exists a `sruct AddrIncomping` together with an implementation of `Accept` for `AddrIncoming`. I really don't know what I am doing here, as I am very new to Rust and simply tries to solve the problem. The mentioned errors disappear after adding the code, but I get a new error message, as `poll_next()` is not implemented for `AddrIncoming`. There exists an implementation of `poll_next()` is the same file mentioned above but I don't know enough about Rust to understand that code, and simply coping and pasting the code does not work, too.
I would be very happy, if You got the time to update Your code. The code looks really simple to use and easier than other solutions but the implementation is too difficult to understand for me currently.

Furthermore, I want to mention that the crates `tokio-reactor`, `tokio-tls`, `tokio-tcp`, `tokio-io`, and `tokio-timer` are all deprecated and moved into tokio. Of course, it would make sense to update these dependencies of `hyper-tls-hack`, too, but it is not as important as to remove the errors above.

**Comment by miquels** [comment]
Yes, things have changed a lot in newer tokio/hyper crates. Fortunately there's another crate that does for hyper 0.14 what this crate did for hyper 0.11: [tls-listener](https://docs.rs/tls-listener/0.2.1/tls_listener/). I did find [one bug](https://github.com/tmccombs/tls-listener/issues/3) in it, let's hope that the author is responsive.

You can find examples on how to use it in the examples/ directory of the tls-listener crate, or otherwise you can look at main.c and tls.c of my [webdav-server](https://github.com/miquels/webdav-server-rs) crate.

In the mean time I'm going to archive this repository.
